"""
   .-') _   .-') _   .-') _   .-') _   .-') _   .-') _
  (  OO) ) (  OO) ) (  OO) ) (  OO) ) (  OO) ) (  OO) )
 ,------'  ,------'  ,------'  ,------'  ,------'  ,------'
 |  .---'  |  .---'  |  .---'  |  .---'  |  .---'  |  .---'
 |  |      |  |      |  |      |  |      |  |      |  |
 |  `--.   |  `--.   |  `--.   |  `--.   |  `--.   |  `--.
 |  .--'   |  .--'   |  .--'   |  .--'   |  .--'   |  .--'
 |  `---.  |  `---.  |  `---.  |  `---.  |  `---.  |  `---.
 `------'  `------'  `------'  `------'  `------'  `------'
    WARNING: This file is auto-generated by the AI assistant.
    Any manual edits may be overwritten in future conversations.
"""
import os
import json
from datetime import datetime, timezone
from typing import Optional
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func, delete, or_, and_
from app.models.application import UserApplication, ApplicationMaterial
from app.models.policy import Policy, PolicyMetadata


UPLOAD_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
    "uploads", "materials"
)


class ApplicationService:
    """申请进度跟踪服务"""

    def __init__(self, db: AsyncSession):
        self.db = db

    async def start_application(self, user_id: int, policy_id: int) -> UserApplication:
        """学生开始准备申请"""
        # 检查是否已申请过
        result = await self.db.execute(
            select(UserApplication).where(
                UserApplication.user_id == user_id,
                UserApplication.policy_id == policy_id,
                UserApplication.status.in_(["preparing", "submitted", "pending_review", "needs_revision", "初审通过", "pending_final", "pending_admin"]),
            )
        )
        existing = result.scalar_one_or_none()
        if existing:
            raise ValueError("您已申请过该政策，请勿重复申请")

        # 检查政策是否存在且已发布
        policy = await self.db.get(Policy, policy_id)
        if not policy or policy.status != "published":
            raise ValueError("政策不存在或未发布")

        # 创建申请
        app = UserApplication(
            user_id=user_id,
            policy_id=policy_id,
            status="preparing",
            applied_at=datetime.now(timezone.utc),
        )
        self.db.add(app)
        await self.db.flush()
        await self.db.refresh(app)

        # 根据政策元数据创建材料清单条目
        meta_result = await self.db.execute(
            select(PolicyMetadata).where(PolicyMetadata.policy_id == policy_id)
        )
        metadata = meta_result.scalar_one_or_none()
        if metadata and metadata.material_list:
            for name in metadata.material_list:
                material = ApplicationMaterial(
                    application_id=app.application_id,
                    material_name=name,
                    upload_status="not_uploaded",
                )
                self.db.add(material)

        await self.db.commit()
        return app

    async def upload_material(self, application_id: int, material_name: str,
                               file_content: bytes, filename: str) -> ApplicationMaterial:
        """上传某项材料"""
        # 查找对应的材料条目
        result = await self.db.execute(
            select(ApplicationMaterial).where(
                ApplicationMaterial.application_id == application_id,
                ApplicationMaterial.material_name == material_name,
            )
        )
        material = result.scalar_one_or_none()
        if not material:
            raise ValueError(f"材料 '{material_name}' 不存在")

        # 保存文件
        app_dir = os.path.join(UPLOAD_DIR, str(application_id))
        os.makedirs(app_dir, exist_ok=True)
        file_path = os.path.join(app_dir, f"{material_name}_{filename}")
        # 避免文件名冲突
        if os.path.exists(file_path):
            base, ext = os.path.splitext(filename)
            file_path = os.path.join(app_dir, f"{material_name}_{base}_{int(time.time())}{ext}")

        with open(file_path, "wb") as f:
            f.write(file_content)

        material.file_name = filename
        material.file_path = file_path
        material.file_size = len(file_content)
        material.upload_status = "uploaded"
        material.uploaded_at = datetime.now(timezone.utc)
        await self.db.commit()
        return material

    async def delete_material(self, application_id: int, material_name: str) -> None:
        """删除已上传的材料"""
        result = await self.db.execute(
            select(ApplicationMaterial).where(
                ApplicationMaterial.application_id == application_id,
                ApplicationMaterial.material_name == material_name,
            )
        )
        material = result.scalar_one_or_none()
        if not material:
            raise ValueError("材料不存在")

        # 删除文件
        if material.file_path and os.path.exists(material.file_path):
            os.remove(material.file_path)

        material.file_name = None
        material.file_path = None
        material.file_size = None
        material.upload_status = "not_uploaded"
        material.uploaded_at = None
        await self.db.commit()

    async def submit_application(self, application_id: int) -> UserApplication:
        """提交电子版申请"""
        result = await self.db.execute(
            select(UserApplication).where(UserApplication.application_id == application_id)
        )
        app = result.scalar_one_or_none()
        if not app:
            raise ValueError("申请不存在")
        if app.status != "preparing":
            raise ValueError(f"当前状态为'{app.status}'，不可提交")

        # 检查是否所有材料都已上传
        materials = await self.db.execute(
            select(ApplicationMaterial).where(
                ApplicationMaterial.application_id == application_id,
                ApplicationMaterial.upload_status != "uploaded",
            )
        )
        missing = materials.scalars().all()
        if missing:
            names = [m.material_name for m in missing]
            raise ValueError(f"以下材料尚未上传：{'、'.join(names)}")

        app.status = "submitted"
        app.submitted_at = datetime.now(timezone.utc)
        await self.db.commit()
        await self.db.refresh(app)
        return app

    async def abandon_application(self, application_id: int) -> UserApplication:
        """放弃申请"""
        result = await self.db.execute(
            select(UserApplication).where(UserApplication.application_id == application_id)
        )
        app = result.scalar_one_or_none()
        if not app:
            raise ValueError("申请不存在")
        if app.status not in ("preparing", "submitted", "needs_revision"):
            raise ValueError(f"当前状态为'{app.status}'，不可放弃")
        app.status = "abandoned"
        await self.db.commit()
        await self.db.refresh(app)
        return app

    async def get_user_applications(self, user_id: int) -> list[dict]:
        """获取用户的所有申请"""
        result = await self.db.execute(
            select(UserApplication)
            .where(UserApplication.user_id == user_id)
            .order_by(UserApplication.created_at.desc())
        )
        apps = result.scalars().all()

        items = []
        for app in apps:
            policy = await self.db.get(Policy, app.policy_id)
            # 获取材料状态
            mats = await self.db.execute(
                select(ApplicationMaterial).where(
                    ApplicationMaterial.application_id == app.application_id
                )
            )
            materials = mats.scalars().all()
            total = len(materials)
            uploaded = sum(1 for m in materials if m.upload_status == "uploaded")

            items.append({
                "application_id": app.application_id,
                "policy_id": app.policy_id,
                "policy_title": policy.title if policy else "",
                "status": app.status,
                "applied_at": app.applied_at.isoformat() if app.applied_at else None,
                "submitted_at": app.submitted_at.isoformat() if app.submitted_at else None,
                "materials_total": total,
                "materials_uploaded": uploaded,
                "created_at": app.created_at.isoformat() if app.created_at else None,
                "feedback": app.feedback,
            })
        return items

    async def get_application_detail(self, application_id: int) -> Optional[dict]:
        """获取申请详情"""
        result = await self.db.execute(
            select(UserApplication).where(UserApplication.application_id == application_id)
        )
        app = result.scalar_one_or_none()
        if not app:
            return None

        policy = await self.db.get(Policy, app.policy_id)
        mats = await self.db.execute(
            select(ApplicationMaterial).where(
                ApplicationMaterial.application_id == application_id
            )
        )
        materials = mats.scalars().all()

        return {
            "application": {
                "application_id": app.application_id,
                "policy_id": app.policy_id,
                "status": app.status,
                "applied_at": app.applied_at.isoformat() if app.applied_at else None,
                "submitted_at": app.submitted_at.isoformat() if app.submitted_at else None,
                "paper_submitted_at": app.paper_submitted_at.isoformat() if app.paper_submitted_at else None,
                "completed_at": app.completed_at.isoformat() if app.completed_at else None,
                "feedback": app.feedback,
            },
            "policy": {
                "policy_id": policy.policy_id,
                "title": policy.title,
                "department": policy.department,
            } if policy else None,
            "materials": [
                {
                    "material_name": m.material_name,
                    "file_name": m.file_name,
                    "file_size": m.file_size,
                    "upload_status": m.upload_status,
                    "uploaded_at": m.uploaded_at.isoformat() if m.uploaded_at else None,
                    "reject_reason": m.reject_reason,
                }
                for m in materials
            ],
        }

    async def get_status_flow(self, status: str) -> dict:
        """获取状态流转信息"""
        flow = {
            "preparing": {"step": 1, "label": "准备材料", "icon": "📝"},
            "submitted": {"step": 2, "label": "待初审", "icon": "⏳"},
            "pending_review": {"step": 2, "label": "待初审", "icon": "⏳"},
            "needs_revision": {"step": 1, "label": "需修正", "icon": "⚠️"},
            "初审通过": {"step": 3, "label": "初审通过", "icon": "✅"},
            "pending_final": {"step": 4, "label": "待终核", "icon": "⏳"},
            "待终核": {"step": 4, "label": "待终核", "icon": "⏳"},
            "pending_admin": {"step": 5, "label": "校级审批", "icon": "⏳"},
            "completed": {"step": 6, "label": "已完成", "icon": "🎉"},
            "abandoned": {"step": 0, "label": "已放弃", "icon": "🚫"},
        }
        return flow.get(status, {"step": 0, "label": status, "icon": "❓"})

import time